# Generated by Django 5.0.6 on 2024-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Contenido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
