# Generated by Django 5.0.6 on 2024-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='Titulo',
            field=models.CharField(max_length=90),
        ),
    ]
