# Generated by Django 5.0.6 on 2024-07-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categoria_nombre_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
