# Generated by Django 5.0.6 on 2024-07-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=80),
        ),
    ]
